# utils/constants.py
VOICE_ACCENTS = {
    "Bella": "British",
    "Joseph": "African",
    "Matilda": "African",
    "Fisayo": "Nigerian",
    "Olabisi": "Nigerian",
    "timi": "Nigerian",
}

REPLACEMENTS = [
    ("i cannot understand", "i no fit understand"),
    ("i cannot speak", "i no fit talk"),
    ("i cannot come", "i no fit come"),
    ("i cannot do", "i no fit do"),
    ("i cannot eat", "i no fit chop"),
    ("i cannot go", "i no fit go"),
    ("i cannot hear", "i no fit hear"),
    ("i cannot see", "i no fit see"),
    ("i cannot", "i no fit"),
    ("i can't", "i no fit"),
    ("i do not want", "i no wan"),
    ("i do not have", "i no get"),
    ("i do not", "i no"),
    ("i don't", "i no"),
    ("what is happening", "wetin dey happen"),
    ("how are you", "how yu dey"),
    ("i'm fine", "i dey kampe"),
    ("are you", "yu dey"),
    ("have you", "yu don"),
    ("do you", "yu dey"),
    ("i want to", "i wan"),
    ("i should", "i suppose"),
    ("i would", "i go"),
    ("i might", "i fit"),
    ("i may", "i fit"),
    ("i must", "i gatz"),
    ("i want", "i wan"),
    ("i need", "i need"),
    ("she will", "she go"),
    ("he will", "him go"),
    ("it will", "e go"),
    ("they will", "dem go"),
    ("we will", "we go"),
    ("i will", "i go"),
    ("she is", "she dey"),
    ("it is", "e dey"),
    ("they are", "dem dey"),
    ("he is", "him dey"),
    ("we are", "we dey"),
    ("i'm", "i dey"),
    ("are", "dey"),
    ("i had", "i don get"),
    ("i have", "i don"),
    ("going", "dey go"),
    ("coming", "dey come"),
    ("i can", "i fit"),
    ("i could", "i fit"),
    ("you", "yu"),
    ("just", "jus"),
    ("good", "beta"),
    ("very good", "too beta"),
    ("friend", "padi"),
    # New additions
    ("i am happy", "i dey happy"),
    ("i am sad", "i dey sad"),
    ("where are you", "wey yu dey"),
    ("what is this", "wetin be dis"),
    ("i like it", "i like am"),
    ("i don’t like", "i no like"),
    ("let’s go", "make we go"),
    ("thank you", "tanks"),
    ("please", "abeg"),
    ("yes", "yes o"),
    ("no", "no o"),
    ("today", "tiday"),
    ("tomorrow", "tumoro"),
    ("yesterday", "yestaday"),
    ("how much", "how mush"),
    ("i am tired", "i don tire"),
    ("i am hungry", "i dey hungry"),
    ("help me", "help me abeg"),
    ("i know", "i sabi"),
    ("i don’t know", "i no sabi"),
    ("come here", "come hia"),
    ("go away", "comot"),
    ("big", "big pass"),
    ("small", "small pass"),
    ("fast", "quick"),
    ("slow", "slow pass"),
    ("beautiful", "fine pass"),
    ("ugly", "ugly pass"),
    ("money", "mone"),
    ("food", "chop chop"),
    ("water", "wata"),
    ("house", "haus"),
    ("car", "keke"),
    ("work", "waka"),
    ("play", "joi"),
    ("sleep", "sabi"),
    ("wake up", "wake o"),
    ("love", "luv"),
    ("hate", "hate pass"),
    ("time", "tun"),
    ("now", "now now"),
    ("later", "bicos"),
]